---
title: "migrationspakt_youtube"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(tuber)
library(rvest)
library(httr)
library(devtools)
yt_oauth(app_id = "", app_secret = "", token = "")
```

```{r}
dates = seq(as.Date("2018-04-01"), as.Date("2018-10-31"), by="days")
starts = str_c(dates, "T00:00:00Z")
ends = str_c(dates, "T23:59:59Z")
migr_df = data.frame()
for(i in c(1:214)){
  start = starts[i]
  end = ends[i]
  df = yt_search("migrationspakt", published_after = start, published_before = end)
  print(start)
  migr_df = bind_rows(migr_df, df)
}
```

```{r}
source_url("https://raw.githubusercontent.com/voskresenskiy/migrationspakt/master/captions.R")
comments = data.frame()
captions = data.frame()

for (i in as.character(migr_df$video_id[1:5])){
  tryCatch({
  c = get_all_comments(video_id = i)
  comments = bind_rows(c, comments)
  par = na.omit(unique(c$parentId))
  for(j in par){
    c_p = get_comments(filter = c(comment_id = j))
    if(nrow(c_p[!(c_p$id %in% c$id),]) > 0){
      comments = bind_rows(comments, c_p)
    }
  }
  cap = get_captions_modified(i)
  if(str_length(cap) > 5){
    captions = rbind(captions, data.frame(video_id = i, captions = cap))
  }
  print(i)
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
```

